/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "coming-soon": () => import("@/views/_builtin/coming-soon/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  log_loginlog: () => import("@/views/log/loginlog/index.vue"),
  log_operlog: () => import("@/views/log/operlog/index.vue"),
  monitor_job: () => import("@/views/monitor/job/index.vue"),
  monitor_server: () => import("@/views/monitor/server/index.vue"),
  storage_config: () => import("@/views/storage/config/index.vue"),
  storage_file: () => import("@/views/storage/file/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_dept: () => import("@/views/system/dept/index.vue"),
  system_dict: () => import("@/views/system/dict/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_notice: () => import("@/views/system/notice/index.vue"),
  system_post: () => import("@/views/system/post/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
