/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'coming-soon',
    path: '/coming-soon',
    component: 'layout.base$view.coming-soon',
    meta: {
      title: 'coming-soon',
      i18nKey: 'route.coming-soon'
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log'
    },
    children: [
      {
        name: 'log_loginlog',
        path: '/log/loginlog',
        component: 'view.log_loginlog',
        meta: {
          title: 'log_loginlog',
          i18nKey: 'route.log_loginlog'
        }
      },
      {
        name: 'log_operlog',
        path: '/log/operlog',
        component: 'view.log_operlog',
        meta: {
          title: 'log_operlog',
          i18nKey: 'route.log_operlog'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_job',
        path: '/monitor/job',
        component: 'view.monitor_job',
        meta: {
          title: 'monitor_job',
          i18nKey: 'route.monitor_job'
        }
      },
      {
        name: 'monitor_server',
        path: '/monitor/server',
        component: 'view.monitor_server',
        meta: {
          title: 'monitor_server',
          i18nKey: 'route.monitor_server'
        }
      }
    ]
  },
  {
    name: 'storage',
    path: '/storage',
    component: 'layout.base',
    meta: {
      title: 'storage',
      i18nKey: 'route.storage'
    },
    children: [
      {
        name: 'storage_config',
        path: '/storage/config',
        component: 'view.storage_config',
        meta: {
          title: 'storage_config',
          i18nKey: 'route.storage_config'
        }
      },
      {
        name: 'storage_file',
        path: '/storage/file',
        component: 'view.storage_file',
        meta: {
          title: 'storage_file',
          i18nKey: 'route.storage_file'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  }
];
